# 全局规划器
GlobalPlanner:                # Also see: http://wiki.ros.org/global_planner
  old_navfn_behavior: false   # 如果出于某种原因，您希望global_planner完全反映navfn的行为，请将其设置为 true（并对其他布尔参数使用默认值）
  use_quadratic: true         # 如果为真，使用势的二次近似。否则，使用更简单的计算。
  use_dijkstra: true          # 如果为真，使用dijkstra 算法。否则，A*(将use_grid_path设为true)。
  use_grid_path: false        # 如果为真，则创建一条遵循网格边界的路径。否则，使用梯度下降法。

  #  指定是否允许规划器创建遍历未知空间的规划。注意：如果您使用带有体素或障碍层的分层costmap_2d 成本图，
  #  您还必须将该层的 track_unknown_space 参数设置为真，否则它将所有未知空间转换为可用空间
  allow_unknown:  true

  planner_window_x: 0.0       # default 0.0
  planner_window_y: 0.0       # default 0.0
  default_tolerance: 0.0      # 计划者目标点的容差。计划者将尝试创建一个尽可能接近指定目标但不超过default_tolerance的计划

  visualize_potential: false  # 指定是否可视化通过 PointCloud2 计算的潜在区域。
